export interface Logo {
  /** Company / fund name — also used as the image alt text. */
  name: string;
  /** File in `public/images/logos/`, generated by `scripts/extract-logos.mjs`. */
  src: string;
  /** Intrinsic pixel size, so the grid never shifts while logos decode. */
  width: number;
  height: number;
  /**
   * Optical size nudge on the shared row height. A square mark set to the same
   * height as a wordmark reads much *smaller*, because a wordmark earns its
   * presence from width — so the near-square marks (Apple, Tesla, Snap,
   * Paramount) are scaled up, and unusually wide or full-height wordmarks are
   * pulled back.
   */
  scale?: number;
}

/** Funds and companies VEST works with — the "Trusted by" strip under the hero. */
export const partnerLogos: Logo[] = [
  { name: "a16z", src: "/images/logos/a16z.png", width: 235, height: 96 },
  { name: "Y Combinator", src: "/images/logos/ycombinator.png", width: 457, height: 96 },
  { name: "8VC", src: "/images/logos/8vc.png", width: 239, height: 96, scale: 0.95 },
  { name: "Windsurf", src: "/images/logos/windsurf.png", width: 576, height: 68, scale: 0.9 },
  { name: "Manus", src: "/images/logos/manus.png", width: 345, height: 96 },
  { name: "Oligo Space", src: "/images/logos/oligo.png", width: 244, height: 96, scale: 1.1 },
];

/**
 * Where members have gone on to work — the "Working at the best companies in
 * tech" grid. Ordered by recognisability so the strongest names land in the
 * first rows once the grid reflows on narrow screens.
 */
export const companyLogos: Logo[] = [
  { name: "Apple", src: "/images/logos/apple.png", width: 98, height: 120, scale: 1.5 },
  { name: "Google", src: "/images/logos/google.png", width: 362, height: 120 },
  { name: "Meta", src: "/images/logos/meta.png", width: 600, height: 120 },
  { name: "Amazon", src: "/images/logos/amazon.png", width: 395, height: 120 },
  { name: "NVIDIA", src: "/images/logos/nvidia.png", width: 653, height: 120, scale: 1.05 },
  { name: "Tesla", src: "/images/logos/tesla.png", width: 92, height: 120, scale: 1.7 },
  { name: "Stripe", src: "/images/logos/stripe.png", width: 289, height: 120 },
  { name: "Coinbase", src: "/images/logos/coinbase.png", width: 660, height: 120 },
  { name: "Vercel", src: "/images/logos/vercel.png", width: 528, height: 120 },
  { name: "Cursor", src: "/images/logos/cursor.png", width: 578, height: 120 },
  { name: "Anduril", src: "/images/logos/anduril.png", width: 655, height: 120 },
  { name: "Scale AI", src: "/images/logos/scale-ai.png", width: 372, height: 120 },
  { name: "Snap", src: "/images/logos/snap.png", width: 119, height: 120, scale: 1.45 },
  { name: "BlackRock", src: "/images/logos/blackrock.png", width: 720, height: 102 },
  { name: "Capital One", src: "/images/logos/capital-one.png", width: 335, height: 120, scale: 1.15 },
  { name: "Deloitte", src: "/images/logos/deloitte.png", width: 638, height: 120 },
  { name: "Northrop Grumman", src: "/images/logos/northrop-grumman.png", width: 535, height: 120, scale: 1.35 },
  { name: "Leidos", src: "/images/logos/leidos.png", width: 497, height: 120 },
  { name: "Caterpillar", src: "/images/logos/caterpillar.png", width: 225, height: 120, scale: 1.25 },
  { name: "Paramount", src: "/images/logos/paramount.png", width: 153, height: 120, scale: 1.7 },
  { name: "Optiver", src: "/images/logos/optiver.png", width: 522, height: 120 },
  { name: "Polymarket", src: "/images/logos/polymarket.png", width: 554, height: 120 },
  { name: "Harvey", src: "/images/logos/harvey.png", width: 397, height: 120 },
  { name: "Mercor", src: "/images/logos/mercor.png", width: 570, height: 120 },
  { name: "Etched", src: "/images/logos/etched.png", width: 595, height: 120 },
  { name: "Browserbase", src: "/images/logos/browserbase.png", width: 479, height: 120 },
  { name: "SafetyKit", src: "/images/logos/safetykit.png", width: 600, height: 120 },
];
